name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Setup Android SDK manually
        run: |
          mkdir -p $HOME/android-sdk
          curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip cmdline-tools.zip -d $HOME/android-sdk
          mv $HOME/android-sdk/cmdline-tools $HOME/android-sdk/tools
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}
          ANDROID_SDK_ROOT: $HOME/android-sdk

      - name: Accept licenses
        run: yes | $HOME/android-sdk/tools/bin/sdkmanager --licenses

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
